sudo: false
language: node_js
node_js:
  - "node"
  - "6"
  - "4"
before_install: npm install -g npm@'>=2.7.4'
script: npm test -- --browsers PhantomJS,Firefox
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
